# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 627e7d42c97e7208659cd31c81120318e9b3a08634a4b22b927bff6643e6daad625017a31f8ec7dd8042104f2808ab314ec71199471147b80b60b7f65f9bde14

test:
  secret_key_base: 792523e0689c2032d7244d9d0f3f439795b76beac141bc4e7c4d510a93df749713e83d7965e96b999891157e578287098365d87b45b9b286798e0d135114070a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
